#!/usr/bin/env bash

# パイプ途中も含めて失敗、未定義変数を検出
set -euo pipefail

# 使い方:
#   ./setup.sh         : 初期構築（従来動作）
#   ./setup.sh attach  : atcoder-nim コンテナへ入り、dev tmux を IDE 2ペインで復帰

# このスクリプト自身のディレクトリを作業ルートにする
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${SCRIPT_DIR}"
PARENT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
NIM_LIB_DIR="${PARENT_DIR}/cp-nim-lib"
SOLVED_LOG_DIR="${PARENT_DIR}/cp-solved-log"

# docker compose 実行は、可能なら sudo なしを優先し、必要時だけ sudo を使う。
compose_cmd() {
  if docker compose version >/dev/null 2>&1; then
    docker compose "$@"
  else
    sudo docker compose "$@"
  fi
}

# atcoder-nim 専用の tmux レイアウト（上 nvim / 下 shell）を復帰・接続する。
# この挙動は atcoder-nim-env 側に閉じ込め、汎用 dotfiles へは漏らさない。
attach_competitive_ide() {
  compose_cmd up -d atcoder-nim

  compose_cmd exec -it atcoder-nim zsh -lc '
PROJECT_DIR="/home/sukenori/atcoder-nim-env"
SOCKET="/tmp/nvimsocket"

start_owner_nvim() {
  tmux respawn-pane -k -t dev:0.0 -c "${PROJECT_DIR}" "zsh -lc '\''while :; do NVIM_LISTEN_ADDRESS=\"${NVIM_SOCKET_PATH:-/tmp/nvimsocket}\" command nvim; sleep 0.05; done'\''"
}

ensure_two_panes() {
  local pane_count
  pane_count="$(tmux list-panes -t dev:0 2>/dev/null | wc -l)"
  if [ "${pane_count}" -lt 2 ]; then
    tmux split-window -v -t dev:0 -c "${PROJECT_DIR}" "zsh -l; tmux kill-session -t dev"
  fi
}

setup_lower_pane() {
  # 下ペインは起動時にソケット情報だけ渡し、関数定義は zshrc 側で行う。
  tmux respawn-pane -k -t dev:0.1 -c "${PROJECT_DIR}" "NVIM_SOCKET_PATH=${SOCKET} zsh -l; tmux kill-session -t dev"
}

if ! tmux has-session -t dev 2>/dev/null; then
  tmux new-session -d -s dev -n main -c "${PROJECT_DIR}" "zsh -lc '\''while :; do NVIM_LISTEN_ADDRESS=\"${NVIM_SOCKET_PATH:-/tmp/nvimsocket}\" command nvim; sleep 0.05; done'\''"
  tmux split-window -v -t dev:0 -c "${PROJECT_DIR}" "zsh -l; tmux kill-session -t dev"
fi

# セッション復帰時にも同じ 2 ペイン運用を再構成する。
ensure_two_panes
tmux set-option -t dev -g set-clipboard on
tmux set-option -t dev -ga terminal-features ",*:clipboard" 2>/dev/null || true
tmux set-option -t dev -ga terminal-overrides ",*:Ms=\E]52;c;%p2%s\a" 2>/dev/null || true
tmux set-option -t dev -g allow-passthrough on 2>/dev/null || true
tmux set-environment -t dev NVIM_SOCKET_PATH "${SOCKET}"
start_owner_nvim
setup_lower_pane

# 復帰時は下ペインへフォーカスして、nvim 実行が上ペインへ飛ぶ運用に寄せる。
tmux select-pane -t dev:0.1
tmux attach-session -t dev
'
}

MODE="${1:-setup}"
if [ "${MODE}" = "attach" ]; then
  attach_competitive_ide
  exit 0
fi

# cp-nim-lib と cp-solved-log を取得・更新
ensure_repo() {
  local url="$1"
  local dir="$2"

  if [ -d "$dir/.git" ]; then
    git -C "$dir" pull --ff-only
    return
  fi

  if [ -e "$dir" ]; then
    echo "$dir が既に存在しますが Git リポジトリではないため中断します。" >&2
    return 1
  fi

  git clone "$url" "$dir"
}

ensure_repo "https://github.com/sukenori/cp-nim-lib.git" "${NIM_LIB_DIR}"
ensure_repo "https://github.com/sukenori/cp-solved-log.git" "${SOLVED_LOG_DIR}"

# ripgrep の検索スコープを更新する（project-local）
SCOPE_FILE="${SCRIPT_DIR}/.nvim/ripgrep_scope_dirs.txt"
mkdir -p "$(dirname "${SCOPE_FILE}")"
{
  echo "# generated by atcoder-nim-env/setup.sh"
  echo "${SCRIPT_DIR}"
  echo "${NIM_LIB_DIR}"
  echo "${SOLVED_LOG_DIR}"
} > "${SCOPE_FILE}"

# 作業ディレクトリを作る
mkdir -p ./work
mkdir -p ./test

# bundle スクリプトに実行権限を付与
[ -f ./bundle.sh ] && chmod +x ./bundle.sh

# 開発コンテナをビルドして起動する
compose_cmd up -d --build atcoder-nim
