#!/usr/bin/env bash

# パイプ途中も含めて失敗、未定義変数を検出
set -euo pipefail

# cp-nim-lib と cp-solved-log を取得
NIM_LIB_DIR="../cp-nim-lib"
SOLVED_LOG_DIR="../cp-solved-log"
git clone "https://github.com/sukenori/cp-nim-lib.git" "${NIM_LIB_DIR}"
git clone "https://github.com/sukenori/cp-solved-log.git" "${SOLVED_LOG_DIR}"

# ripgrep の検索スコープを更新する（project-local）
SCOPE_FILE="${SCRIPT_DIR}/.nvim/ripgrep_scope_dirs.txt"
mkdir -p "$(dirname "${SCOPE_FILE}")"
{
  echo "# generated by atcoder-nim-env/setup.sh"
  echo "${NIM_LIB_DIR}"
  echo "${SOLVED_LOG_DIR}"
} > "${SCOPE_FILE}"

# 作業ディレクトリを作る
mkdir -p ./work
mkdir -p ./test

# bundle スクリプトに実行権限を付与
[ -f ./bundle.sh ] && chmod +x ./bundle.sh

# 開発コンテナをビルドして起動する
sudo docker compose up -d --build atcoder-nim