#!/usr/bin/env bash

# パイプ途中も含めて失敗、未定義変数を検出
set -euo pipefail

# このスクリプト自身のディレクトリを作業ルートにする
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${SCRIPT_DIR}"
PARENT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
NIM_LIB_DIR="${PARENT_DIR}/cp-nim-lib"
SOLVED_LOG_DIR="${PARENT_DIR}/cp-solved-log"

# cp-nim-lib と cp-solved-log を取得・更新
ensure_repo() {
  local url="$1"
  local dir="$2"

  if [ -d "$dir/.git" ]; then
    git -C "$dir" pull --ff-only
    return
  fi

  if [ -e "$dir" ]; then
    echo "$dir が既に存在しますが Git リポジトリではないため中断します。" >&2
    return 1
  fi

  git clone "$url" "$dir"
}

ensure_repo "https://github.com/sukenori/cp-nim-lib.git" "${NIM_LIB_DIR}"
ensure_repo "https://github.com/sukenori/cp-solved-log.git" "${SOLVED_LOG_DIR}"

# Telescope の優先検索スコープを更新する（project-local）
SCOPE_FILE="${SCRIPT_DIR}/.nvim/telescope_priority_dirs.txt"
mkdir -p "$(dirname "${SCOPE_FILE}")"
{
  echo "# generated by atcoder-nim-env/setup.sh"
  echo "${SCRIPT_DIR}"
  echo "${NIM_LIB_DIR}"
  echo "${SOLVED_LOG_DIR}"
} > "${SCOPE_FILE}"

# 作業ディレクトリを作る
mkdir -p ./work
mkdir -p ./test

# bundle スクリプトに実行権限を付与
[ -f ./bundle.sh ] && chmod +x ./bundle.sh

# 開発コンテナをビルドして起動する
sudo docker compose up -d --build atcoder-nim
